#ifndef __TX_ERR_H__ 
#define __TX_ERR_H__ 

#define SET_FEE_RATE_BASE				0
#define SET_FEE_RATE_INVALID_VALUE		(SET_FEE_RATE_BASE + 0x01)
#define BASE58_DECODE_BASE				0
#define BASE58_DECODE_OUT_OF_RANGE		(BASE58_DECODE_BASE + 0x01)		//buffer out of range
#define ADDRESS_VERIFY_BASE				0
#define ADDRESS_VERIFY_DECODE			(ADDRESS_VERIFY_BASE + 0x01)
#define ADDRESS_VERIFY_CHECKSUM			(ADDRESS_VERIFY_BASE + 0x02)
#define ADDR_TO_PUBKEY_HASH_BASE		0
#define ADDR_TO_PUBKEY_HASH_ADDR		(ADDR_TO_PUBKEY_HASH_BASE + 0x01)
#define SIGNATURE_BASE					0
#define SIGNATURE_FAIL					(SIGNATURE_BASE + 0x01)
#define PUBKEY_BASE						0
#define SET_PRIKEY_BASE					0
#define SET_PRIKEY_UNKNOWN_SCRIPTPUB	(SET_PRIKEY_BASE + 0x01)
#define SET_PRIKEY_UNKNOWN_KEY			(SET_PRIKEY_BASE + 0x02)
#define SET_PRIKEY_APDU_FAIL			(SET_PRIKEY_BASE + 0x03)
#define TXGEN_BASE						0
#define TXGEN_NOT_ENOUOH_INPUTS			(TXGEN_BASE + 0x01)
#define TXGEN_SIGFAIL					(TXGEN_BASE + 0x02)
#define TXGEN_PUBFAIL					(TXGEN_BASE + 0x03)
#define COIN_SELECT_BASE                0
#define COIN_SELECT_NOT_ENOUOH_INPUTS   (COIN_SELECT_BASE + 0x01)

#endif 
